apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-application

spec:
  replicas: 3

  selector:
    matchLabels:
      app: demo-application

  template:
    metadata:
      labels:
        app: demo-application
    spec:
      containers:
      - name: demo-application
        image: creddy1140/demo:latest
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
---
    apiVersion: v1
    kind: Service
    metadata:
      name: demo-application
    spec:
      selector:
        app: demo-application
      ports:
      - name: http
        port: 8080
        targetPort: 8080
      type: LoadBalancer