apiVersion: v1
    kind: Service
    metadata:
      name: demo-application
    spec:
      selector:
        app: demo-application
      ports:
      - name: http
        port: 80
        targetPort: 80
      type: LoadBalancer
